export const colors = {
  brand: '#2563eb',
  brandDark: '#1d4ed8',
  brandSoft: '#e8f0fe',
  accent: '#06b6d4',
  accentSoft: '#e0f7fc',
  navy: '#0a1e46',
  navySoft: '#123189',
  bg: '#f3f7fd',
  card: '#ffffff',
  border: '#dde6f3',
  text: '#0f1c33',
  textSoft: '#3d4d68',
  textFaint: '#7487a5',
  success: '#0ea878',
  successSoft: '#dcfcee',
  danger: '#e24545',
  dangerSoft: '#fee8e8',
  warning: '#e79a09',
  warningSoft: '#fef3d8',
  info: '#0284c7',
  infoSoft: '#e0f2fe',
  purple: '#7c3aed',
  purpleSoft: '#f1e9fe',
};

export const STATUS_COLORS: Record<string, { bg: string; fg: string }> = {
  planning: { bg: colors.infoSoft, fg: colors.info },
  in_progress: { bg: colors.warningSoft, fg: '#a97e00' },
  on_hold: { bg: colors.warningSoft, fg: '#a97e00' },
  completed: { bg: colors.successSoft, fg: colors.success },
  cancelled: { bg: colors.dangerSoft, fg: colors.danger },
  pending: { bg: colors.infoSoft, fg: colors.info },
  delayed: { bg: colors.dangerSoft, fg: colors.danger },
  open: { bg: colors.infoSoft, fg: colors.info },
  assigned: { bg: colors.purpleSoft, fg: colors.purple },
  resolved: { bg: colors.successSoft, fg: colors.success },
  reopened: { bg: colors.dangerSoft, fg: colors.danger },
  closed: { bg: colors.successSoft, fg: colors.success },
  passed: { bg: colors.successSoft, fg: colors.success },
  failed: { bg: colors.dangerSoft, fg: colors.danger },
  reinspection_required: { bg: colors.warningSoft, fg: '#a97e00' },
  present: { bg: colors.successSoft, fg: colors.success },
  absent: { bg: colors.dangerSoft, fg: colors.danger },
  leave: { bg: colors.infoSoft, fg: colors.info },
  half_day: { bg: colors.warningSoft, fg: '#a97e00' },
  overtime: { bg: colors.purpleSoft, fg: colors.purple },
  low: { bg: colors.infoSoft, fg: colors.info },
  medium: { bg: colors.warningSoft, fg: '#a97e00' },
  high: { bg: colors.dangerSoft, fg: '#c96a10' },
  critical: { bg: colors.dangerSoft, fg: colors.danger },
  paid: { bg: colors.successSoft, fg: colors.success },
  partial: { bg: colors.warningSoft, fg: '#a97e00' },
  unpaid: { bg: colors.dangerSoft, fg: colors.danger },
  approved: { bg: colors.successSoft, fg: colors.success },
  rejected: { bg: colors.dangerSoft, fg: colors.danger },
  submitted: { bg: colors.infoSoft, fg: colors.info },
  synced: { bg: colors.successSoft, fg: colors.success },
  queued: { bg: colors.warningSoft, fg: '#a97e00' },
  error: { bg: colors.dangerSoft, fg: colors.danger },
};

export const spacing = (n: number) => n * 4;
