export const colors = {
  brand: '#e8651a',
  brandDark: '#c24e0e',
  brandSoft: '#fdeee2',
  navy: '#0f1b2d',
  navySoft: '#1c2b40',
  bg: '#f4f6f9',
  card: '#ffffff',
  border: '#e3e8ef',
  text: '#1a2433',
  textSoft: '#5b6b80',
  textFaint: '#8c99ac',
  success: '#1d9d74',
  successSoft: '#e2f6ef',
  danger: '#d64545',
  dangerSoft: '#fce8e8',
  warning: '#e0a800',
  warningSoft: '#fdf3d7',
  info: '#2f80ed',
  infoSoft: '#e7f1fd',
  purple: '#7b4bd6',
  purpleSoft: '#f0eafd',
};

export const STATUS_COLORS: Record<string, { bg: string; fg: string }> = {
  planning: { bg: colors.infoSoft, fg: colors.info },
  in_progress: { bg: colors.warningSoft, fg: '#a97e00' },
  on_hold: { bg: colors.warningSoft, fg: '#a97e00' },
  completed: { bg: colors.successSoft, fg: colors.success },
  cancelled: { bg: colors.dangerSoft, fg: colors.danger },
  pending: { bg: colors.infoSoft, fg: colors.info },
  delayed: { bg: colors.dangerSoft, fg: colors.danger },
  open: { bg: colors.infoSoft, fg: colors.info },
  assigned: { bg: colors.purpleSoft, fg: colors.purple },
  resolved: { bg: colors.successSoft, fg: colors.success },
  reopened: { bg: colors.dangerSoft, fg: colors.danger },
  closed: { bg: colors.successSoft, fg: colors.success },
  passed: { bg: colors.successSoft, fg: colors.success },
  failed: { bg: colors.dangerSoft, fg: colors.danger },
  reinspection_required: { bg: colors.warningSoft, fg: '#a97e00' },
  present: { bg: colors.successSoft, fg: colors.success },
  absent: { bg: colors.dangerSoft, fg: colors.danger },
  leave: { bg: colors.infoSoft, fg: colors.info },
  half_day: { bg: colors.warningSoft, fg: '#a97e00' },
  overtime: { bg: colors.purpleSoft, fg: colors.purple },
  low: { bg: colors.infoSoft, fg: colors.info },
  medium: { bg: colors.warningSoft, fg: '#a97e00' },
  high: { bg: colors.dangerSoft, fg: '#c96a10' },
  critical: { bg: colors.dangerSoft, fg: colors.danger },
  paid: { bg: colors.successSoft, fg: colors.success },
  partial: { bg: colors.warningSoft, fg: '#a97e00' },
  unpaid: { bg: colors.dangerSoft, fg: colors.danger },
  approved: { bg: colors.successSoft, fg: colors.success },
  rejected: { bg: colors.dangerSoft, fg: colors.danger },
  submitted: { bg: colors.infoSoft, fg: colors.info },
  synced: { bg: colors.successSoft, fg: colors.success },
  queued: { bg: colors.warningSoft, fg: '#a97e00' },
  error: { bg: colors.dangerSoft, fg: colors.danger },
};

export const spacing = (n: number) => n * 4;
