// BuildTrack mobile theme
// Coral brand + deep blue accent on a warm, light background.
// Adapted from the same base palette the web admin uses, so the
// site, the app, and the office all look like one product.

export const colors = {
  brand: '#ff5b1f',
  brandDark: '#e84a10',
  brandSoft: '#fff0e6',
  brandGlow: 'rgba(255, 91, 31, 0.18)',
  accent: '#0d6cc4',
  accentSoft: '#e8f3fb',
  navy: '#0a1e46',
  navySoft: '#123189',
  bg: '#f6f7fb',
  bgCard: '#ffffff',
  border: '#e3eaf3',
  text: '#0f1c33',
  textSoft: '#3d4d68',
  textFaint: '#6b7d98',
  success: '#0ea878',
  successSoft: '#dcfcee',
  danger: '#e24545',
  dangerSoft: '#fee8e8',
  warning: '#e79a09',
  warningSoft: '#fef3d8',
  info: '#0d6cc4',
  infoSoft: '#e8f3fb',
  purple: '#7c3aed',
  purpleSoft: '#f1e9fe',
};

// Status palette (used by the Badge component). Keys match the
// canonical workflow states used by the ERP backend.
export const STATUS_COLORS: Record<string, { bg: string; fg: string }> = {
  planning:             { bg: colors.infoSoft,    fg: colors.info },
  in_progress:          { bg: colors.warningSoft, fg: '#a97e00' },
  on_hold:              { bg: colors.warningSoft, fg: '#a97e00' },
  completed:            { bg: colors.successSoft, fg: colors.success },
  cancelled:            { bg: colors.dangerSoft,  fg: colors.danger },
  pending:              { bg: colors.infoSoft,    fg: colors.info },
  delayed:              { bg: colors.dangerSoft,  fg: colors.danger },
  open:                 { bg: colors.infoSoft,    fg: colors.info },
  assigned:             { bg: colors.purpleSoft,  fg: colors.purple },
  resolved:             { bg: colors.successSoft, fg: colors.success },
  reopened:             { bg: colors.dangerSoft,  fg: colors.danger },
  closed:               { bg: colors.successSoft, fg: colors.success },
  passed:               { bg: colors.successSoft, fg: colors.success },
  failed:               { bg: colors.dangerSoft,  fg: colors.danger },
  reinspection_required:{ bg: colors.warningSoft, fg: '#a97e00' },
  present:              { bg: colors.successSoft, fg: colors.success },
  absent:               { bg: colors.dangerSoft,  fg: colors.danger },
  leave:                { bg: colors.infoSoft,    fg: colors.info },
  half_day:             { bg: colors.warningSoft, fg: '#a97e00' },
  overtime:             { bg: colors.purpleSoft,  fg: colors.purple },
  low:                  { bg: colors.infoSoft,    fg: colors.info },
  medium:               { bg: colors.warningSoft, fg: '#a97e00' },
  high:                 { bg: colors.brandSoft,   fg: colors.brandDark },
  critical:             { bg: colors.dangerSoft,  fg: colors.danger },
  paid:                 { bg: colors.successSoft, fg: colors.success },
  partial:              { bg: colors.warningSoft, fg: '#a97e00' },
  unpaid:               { bg: colors.dangerSoft,  fg: colors.danger },
  approved:             { bg: colors.successSoft, fg: colors.success },
  rejected:             { bg: colors.dangerSoft,  fg: colors.danger },
  submitted:            { bg: colors.infoSoft,    fg: colors.info },
  synced:               { bg: colors.successSoft, fg: colors.success },
  queued:               { bg: colors.warningSoft, fg: '#a97e00' },
  error:                { bg: colors.dangerSoft,  fg: colors.danger },
  running:              { bg: colors.successSoft, fg: colors.success },
  idle:                 { bg: colors.warningSoft, fg: '#a97e00' },
  breakdown:            { bg: colors.dangerSoft,  fg: colors.danger },
  available:            { bg: colors.successSoft, fg: colors.success },
  deployed:             { bg: colors.infoSoft,    fg: colors.info },
  maintenance:          { bg: colors.warningSoft, fg: '#a97e00' },
};

export const spacing = (n: number) => n * 4;
